output: .
hydra:
    run:
        dir: ${output}
    verbose: true
    job_logging:
        handlers:
            console:
                class: logging.StreamHandler
                formatter: simple
                stream: ext://sys.stdout
            file:
                class: logging.FileHandler
                formatter: simple
                filename: ${hydra.runtime.output_dir}/run.log

calculator:
    _target_: nequip.integrations.ase.NequIPCalculator.from_compiled_model
    compile_path:
        _target_: os.path.expanduser
        path: ~/.local/nequip-oam-0.1/NequIP-OAM-S-0.1.nequip.pth
    chemical_species_to_atom_type_map: true
    device: cpu
adsorption:
    nfibonacci: 100
    max_steps_for_first_stage: 0
    max_steps_for_second_stage: 100
    max_force: 0.05
    debug: false

system:
    atoms:
        _target_: ase.build.fcc111
        symbol: Cu
        size:
            - 10
            - 10
            - 5
        vacuum: 15
        orthogonal: true
        periodic: true
    core:
        - 454
gas: C6H6
