output: .
hydra:
  run:
    dir: ${output}
  verbose: true
  job_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/run.log


calculator:
  _target_: ase.calculators.emt.EMT
adsorption:
  nfibonacci: 100
  max_steps_for_first_stage: 100
  max_steps_for_second_stage: 100
  max_force: 0.05
  debug: false


system:
  atoms:
    _target_: ase.build.fcc111
    symbol: Cu
    size:
      - 10
      - 10
      - 5
    vacuum: 15
    orthogonal: true
    periodic: true
  core:
    - 454
gas:
  C6H6